// Location: frontend/src/hooks/useLanguage.js
import { useContext } from 'react'
import { LanguageContext } from '../context/LanguageContext'

// Inline the locale strings to avoid public/ import issues with Vite
const strings = {
  en: {
    app_name: 'AgroAI',
    what_waste: 'What agro-waste do you have?',
    quantity_kg: 'Quantity (in kg)',
    quality: 'Quality',
    get_location: 'Get My Location',
    location_captured: 'Location captured',
    enter_pincode: 'Enter Pincode',
    analyze: 'Analyze',
    sell_raw: 'Sell as raw material',
    convert: 'Convert to product',
    recommendation: 'Our Recommendation',
    net_profit: 'Net Profit',
    transport_cost: 'Transport Cost',
    days_to_money: 'Days to get money',
    carbon_saved: 'CO₂ Saved',
    call_buyer: 'Call Buyer',
    no_buyers: 'No buyers found nearby',
    price_outdated: '⚠️ Price data may be outdated',
    min_100kg: 'Enter at least 100 kg',
    max_500_tons: 'Maximum 500 tons',
    select_waste_type: 'Select waste type',
    provide_location: 'Please provide your location',
    invalid_pincode: 'Enter a valid 6-digit pincode',
    loading: 'Loading...',
    error_occurred: 'Something went wrong. Please try again.',
    back: 'Back',
    see_buyers: 'See Buyers',
    learn_convert: 'Learn How to Convert',
    select_option: 'Select an option',
    quality_dry: 'Dry (Good)',
    quality_semi: 'Semi-Dry (Fair)',
    quality_wet: 'Wet (Poor)',
    all_options: 'All Options',
    carbon_impact: 'Carbon Impact',
    col_option: 'Option',
    col_time: 'Time',
    ai_assistant: 'AI Assistant',
    consulting_docs: 'Consulting documents...',
    type_question: 'Type your question...',
    send: 'Send',
    assistant_error: 'I encountered an error looking up that specific manual. Please try again.',
    assistant_intro: "Ask me any questions about converting crop residue into valuable resources. I've been trained on ICAR and MNRE manuals.",
    topic_biochar: '🌾 Biochar Guide',
    topic_briquette: '🔥 Briquette Info',
    topic_mushroom: '🍄 Mushroom Cultivation',
    topic_policy: '📜 General Policy',
    // BuyerList specific strings
    nearby_buyers: 'Nearby Buyers',
    offering_price: 'Offering Price',
    pickup: 'Pickup',
    pickup_provided: 'Provided',
    pickup_self: 'You arrange',
    map: 'Map',
    no_buyers_radius: 'No buyers strictly within your radius.',
    showing_distant: 'Showing distant Pilot Network Buyers as a fallback reference. Pilot network currently supports selected regions only.',
    no_buyers_pilot: 'No nearby buyers found in the current pilot network for your waste type.',
    pilot_network: 'Pilot Network',
    paper_mill: 'Paper Mill',
    biomass_plant: 'Biomass Plant',
    compost_facility: 'Compost Facility',
    // Conversion Guide specific strings
    conversion_guide: 'Conversion Guide',
    no_data: 'No data available.',
    how_to_make: 'How to make',
    est_output: 'Estimated Output',
    est_time: 'Estimated Time',
    days: 'Days',
    kg: 'kg',
    fin_breakdown: 'Financial Breakdown',
    exp_revenue: 'Expected Revenue',
    proc_cost: 'Processing Cost',
    est_net_profit: 'Estimated Net Profit',
    resources: 'Resources',
    find_kvk: 'Find Local KVK Center',
    contact_kvk_1: 'Contact your local Krishi Vigyan Kendra (KVK) for specialized training on converting your crop residue into ',
    contact_kvk_2: '.',
    'biochar': 'biochar',
    'briquette': 'briquette',
    'mushroom substrate': 'mushroom substrate',
    ask_ai_guide: 'Need a step-by-step guide?',
    chat_with_agroai: '🤖 Chat with AgroAI',
    ai_guide_desc: 'AgroAI is fully trained on ICAR manual instruction sets to walk you completely through making ',
  },
  hi: {
    app_name: 'एग्रो AI',
    what_waste: 'आपके पास कौन सा कृषि अवशेष है?',
    quantity_kg: 'मात्रा (किलो में)',
    quality: 'गुणवत्ता',
    get_location: 'अपनी लोकेशन दें',
    location_captured: 'लोकेशन मिल गई',
    enter_pincode: 'पिनकोड डालें',
    analyze: 'विश्लेषण करें',
    sell_raw: 'कच्चे माल के रूप में बेचें',
    convert: 'उत्पाद में बदलें',
    recommendation: 'हमारी सलाह',
    net_profit: 'शुद्ध लाभ',
    transport_cost: 'ढुलाई खर्च',
    days_to_money: 'पैसा मिलने में दिन',
    carbon_saved: 'CO₂ बचाया',
    call_buyer: 'खरीदार को कॉल करें',
    no_buyers: 'आस-पास कोई खरीदार नहीं मिला',
    price_outdated: '⚠️ कीमत पुरानी हो सकती है',
    min_100kg: 'कम से कम 100 किलो डालें',
    max_500_tons: 'अधिकतम 500 टन',
    select_waste_type: 'अवशेष का प्रकार चुनें',
    provide_location: 'कृपया अपनी लोकेशन दें',
    invalid_pincode: 'सही 6 अंकों का पिनकोड डालें',
    loading: 'लोड हो रहा है...',
    error_occurred: 'कुछ गलत हो गया। कृपया दोबारा कोशिश करें।',
    back: 'वापस',
    see_buyers: 'खरीदार देखें',
    learn_convert: 'बदलने का तरीका जानें',
    select_option: 'विकल्प चुनें',
    quality_dry: 'सूखा (अच्छा)',
    quality_semi: 'हल्का सूखा (औसत)',
    quality_wet: 'गीला (खराब)',
    all_options: 'सभी विकल्प',
    carbon_impact: 'कार्बन प्रभाव',
    col_option: 'विकल्प',
    col_time: 'समय',
    ai_assistant: 'एआई सहायक',
    consulting_docs: 'दस्तावेजों की जांच कर रहे हैं...',
    type_question: 'अपना प्रश्न टाइप करें...',
    send: 'भेजें',
    assistant_error: 'दस्तावेज़ खोजने में त्रुटि। कृपया पुनः प्रयास करें।',
    assistant_intro: "मुझसे फसल अवशेष को उपयोगी संसाधन बनाने से जुड़ा कोई भी प्रश्न पूछें। मुझे ICAR और MNRE गाइड के आधार पर प्रशिक्षित किया गया है।",
    topic_biochar: '🌾 बायोचार गाइड',
    topic_briquette: '🔥 ब्रिकेट जानकारी',
    topic_mushroom: '🍄 मशरूम की खेती',
    topic_policy: '📜 सरकारी योजनाएं',
    // BuyerList specific strings
    nearby_buyers: 'आस-पास के खरीदार',
    offering_price: 'प्रस्तावित मूल्य',
    pickup: 'पिकअप',
    pickup_provided: 'उपलब्ध है',
    pickup_self: 'खुद व्यवस्था करें',
    map: 'नक्शा',
    no_buyers_radius: 'आपके दायरे में कोई खरीदार नहीं मिला।',
    showing_distant: 'रेफरेंस के लिए दूर के पायलट नेटवर्क खरीदारों को दिखाया जा रहा है। पायलट नेटवर्क अभी चुनिंदा क्षेत्रों में ही उपलब्ध है।',
    no_buyers_pilot: 'आपके अवशेष के प्रकार के लिए वर्तमान पायलट नेटवर्क में कोई खरीदार नहीं मिला।',
    pilot_network: 'पायलट नेटवर्क',
    paper_mill: 'पेपर मिल',
    biomass_plant: 'बायोमास प्लांट',
    compost_facility: 'कम्पोस्ट फैसिलिटी',
    // Seed Data Overrides 
    'GreenFuel Biomass Plant': 'ग्रीनफ्यूल बायोमास प्लांट',
    'Sharma Brick Kiln': 'शर्मा ईंट भट्ठा',
    'EcoCompost Solutions': 'ईकोकम्पोस्ट सॉल्यूशंस',
    'Punjab Paper Mill': 'पंजाब पेपर मिल',
    'Agri Briquette Co.': 'एग्री ब्रिकेट कंपनी',
    'MahaAgro Biomass Fuel': 'महाएग्रो बायोमास फ्यूल',
    'Mumbai Green Energy': 'मुंबई ग्रीन एनर्जी',
    'Nashik Brick Co.': 'नासिक ब्रिक कंपनी',
    'Thane Paper & Pulp': 'ठाणे पेपर एंड पल्प',
    'Punjab': 'पंजाब',
    'Ludhiana': 'लुधियाना',
    'Amritsar': 'अमृतसर',
    'Haryana': 'हरियाणा',
    'Karnal': 'करनाल',
    'Jalandhar': 'जालंधर',
    'UP': 'उत्तर प्रदेश',
    'Meerut': 'मेरठ',
    'Maharashtra': 'महाराष्ट्र',
    'Pune': 'पुणे',
    'Mumbai Suburban': 'मुंबई उपनगर',
    'Nashik': 'नासिक',
    'Thane': 'ठाणे',
    // Conversion Guide specific strings
    conversion_guide: 'परिवर्तन मार्गदर्शिका',
    no_data: 'कोई डेटा उपलब्ध नहीं है।',
    how_to_make: 'बनाने की विधि: ',
    est_output: 'अनुमानित उत्पादन',
    est_time: 'अनुमानित समय',
    days: 'दिन',
    kg: 'किलो',
    fin_breakdown: 'वित्तीय जानकारी',
    exp_revenue: 'संभावित आय',
    proc_cost: 'प्रोसेसिंग खर्च',
    est_net_profit: 'अनुमानित शुद्ध लाभ',
    resources: 'संसाधन',
    find_kvk: 'नजदीकी KVK केंद्र खोजें',
    contact_kvk_1: 'अपने फसल अवशेष को ',
    contact_kvk_2: ' में बदलने के विशेष प्रशिक्षण के लिए अपने स्थानीय कृषि विज्ञान केंद्र (KVK) से संपर्क करें।',
    'biochar': 'बायोचार',
    'briquette': 'ब्रिकेट',
    'mushroom substrate': 'मशरूम सब्सट्रेट',
    ask_ai_guide: 'क्या आपको स्टेप-बाय-स्टेप गाइड चाहिए?',
    chat_with_agroai: '🤖 एग्रो AI से जुड़ें',
    ai_guide_desc: 'ICAR मैनुअल के आधार पर प्रशिक्षित एग्रो AI आपको स्टेप-बाय-स्टेप बताएगा कि इसे कैसे बनाना है: ',
  },
}

export function useLanguage() {
  const { lang, setLang } = useContext(LanguageContext)

  const t = (key) => strings[lang]?.[key] || strings['en']?.[key] || key

  return { lang, setLang, t }
}
